FROM ubuntu:22.04

LABEL author="Yogi"

RUN apt update 
RUN apt install apache2 -y

COPY index.html /var/www/html/index.html
RUN chmod -R /var/www
RUN chmode 644 /var/www/html/index.html

EXPOSE 80

CMD apache2 -DFOREGROUND