FROM ubuntu:22.04

LABEL Developer="Yogi"

RUN apt update -y 
RUN apt install -y npm

RUN git clone https://github.com/shubhamkalsait/devops-fullstack-app.git /opt
WORKDIR frontend

CMD npm start

EXPOSE 3000

