FROM ubuntu:latest

LABEL Developer="Yogi"

RUN apt update -y 
RUN apt install npm -y



RUN git clone https://github.com/shubhamkalsait/devops-fullstack-app.git 
WORKDIR /devops-fullstack-app/frontend/

RUN npm install react-scripts@3.4.1 -g
RUN npm fund

EXPOSE 3000

CMD ["npm" , "start"]  -DFOREGROUND
